<article>
    <h1>Déclaration de confidentialité</h1>
    <section>
        <p><b>Ce site ne nécessite pas d'inscription préalable avant connexion ou navigation. Vous pouvez avoir accès à l'ensemble des données qui sont publiques.</p>

<p>Cependant dans le cas où une évolution du site prévoit de saisir vos données personnelles, vous trouverez ci-dessous la politique de protection des données personnelles en vigueur.</b></p>

<p>POLITIQUE DE PROTECTION DES DONNÉES PERSONNELLES</p>

<p>La présente Politique de protection des données personnelles décrit les méthodes que nous, utilisons pour recueillir, gérer et utiliser les informations sur les visiteurs de notre site Web.</p>

<p>Cette Politique peut être modifiée, complétée, supprimée ou mise à jour ; cependant, nous traiterons toujours vos Informations personnelles conformément à la Politique en vigueur au moment de leur collecte.</p>

<p>Notre objectif est de vous faire part régulièrement sur cette page des modifications éventuelles apportées à cette Politique, afin que vous soyez toujours pleinement informé des catégories d'informations que nous recueillons, de la manière dont nous les utilisons, et des circonstances dans lesquelles elles peuvent être communiquées.</p>

<p>Notre Politique de protection des données se trouve sur notre page d'accueil, mais est également accessible sur chaque page où des Données personnelles sont demandées. Des explications complémentaires sur les finalités pour lesquelles les données seront utilisées, peuvent être fournies à chaque "point de collecte des données" si nécessaire.</p>

<h2>1. Garanties sur la confidentialité des données</h2>

<p>Le terme "Données personnelles", tel qu'il est utilisé dans la présente Politique, fait référence aux informations telles que vos nom, date de naissance, adresse e-mail ou numéro de téléphone, qui permettent de vous identifier. En règle générale, nous traiterons vos Données personnelles selon la procédure décrite dans cette Politique. Nous nous réservons le droit de procéder à des traitements supplémentaires qui seraient requis par la loi, ou dans le cadre d'une enquête notamment pénale.</p>

<p>Les sections suivantes expliquent les modalités de collecte de vos Données personnelles.</p>

<h2>2. Utilisation des Données personnelles</h2>

<p>La plupart de nos services ne requièrent aucune forme d'inscription ou d'enregistrement, ce qui vous permet de visiter notre site sans avoir à vous identifier. Cependant, certains services pourraient nécessiter la communication de certaines Données personnelles. Dans ces cas, si vous choisissez de ne pas communiquer les informations que nous vous demandons, il se peut que vous ne puissiez pas accéder à certaines parties du site, et que nous soyons dans l'impossibilité de répondre à votre demande.</p>

<p>Selon la réglementation locale en vigueur, vos Données personnelles nous permettent de vous fournir des produits ou services, de vous facturer les produits et services demandés, de vous proposer des produits et services susceptibles de vous intéresser ou de communiquer avec vous pour d'autres finalités évidentes compte tenu des circonstances et sur lesquelles nous vous informons lorsque nous recueillons vos Données personnelles.</p>

<h2>3. Non-communication des données personnelles</h2>

<p>Vos Données personnelles ne seront jamais vendues, partagées ou communiquées à des tiers, en dehors des cas prévus par la présente Politique.</p>

<p>Vos Données personnelles pourront également être communiquées à des tiers agissant pour nous ou notre compte dans le cadre d'un traitement spécifique conformément aux finalités pour lesquelles elles ont été recueillies initialement, ou pourront être traitées légalement, selon la réglementation locale en vigueur, dans le cadre d'activités telles que fourniture de services, évaluation de l'utilité de ce site, commercialisation et marketing produit, gestion de données ou support technique. Ces tiers se sont engagés par contrat à n'utiliser vos Données personnelles qu'aux fins convenues, et à ne pas les vendre ou divulguer à d'autres tiers sauf si la loi le requiert, si nous les y autorisons explicitement, ou si une disposition est prévue en ce sens dans la présente Politique.</p>

<h2>4. Droit d'accès, de rectification et d'opposition</h2>

<p>Chaque fois que nous traitons des Données personnelles, nous prenons toutes les mesures raisonnables pour nous assurer de l'exactitude et de la pertinence de vos données conformément aux finalités pour lesquelles nous les collectons. Vous disposez d'un droit d'opposition au traitement de vos Données personnelles pour des raisons légitimes, c'est-à-dire si ce traitement n'est pas raisonnablement nécessaire à la poursuite de notre intérêt légitime tel que décrit dans la présente Politique, ou au respect de la loi. En cas de prospection y compris par voie électronique, nous vous fournirons les moyens vous permettant de vous opposer à recevoir des informations ou d'y consentir, conformément à la loi. Si vous souhaitez savoir comment nous utilisons vos Données personnelles, ou vous opposer au traitement de celles-ci, contactez-nous par email à l'adresse suivante :</p>

<p>contact@datlan.eu</p>

<p>Dans ce cas, veuillez indiquer le nom du site Web sur lequel vous avez communiqué vos informations, ainsi que celles que vous souhaiteriez que nous corrigions, mettions à jour ou supprimions, en vous identifiant de manière précise. Les demandes de suppression de données personnelles seront soumises aux obligations qui nous sont imposées par la loi, notamment en matière de conservation ou d'archivage des documents.</p>

<h2>5. Sécurité et confidentialité</h2>

<p>Pour assurer la sécurité et la confidentialité des Données personnelles que nous recueillons en ligne, nous utilisons des réseaux protégés par des dispositifs standards tels que par pare-feu et mot de passe. Lors du traitement de vos Données personnelles, nous prenons toutes les mesures raisonnables visant à les protéger contre toute perte, utilisation détournée, accès non autorisé, divulgation, altération ou destruction.</p>

<h2>6. Comment nous contacter</h2>

<p>Si vous avez des questions ou des réclamations concernant notre conformité à la présente Politique de confidentialité des données, ou si vous souhaitez nous faire part de recommandations ou des commentaires visant à améliorer sa qualité, contactez-nous par email à l'adresse suivante :</p>

<p>contact@datlan.eu</p>

<p>L'utilisation de ce site est soumise à nos Conditions générales d'Utilisation et à notre Clause de Confidentialité.</p>
    </section>
</article>
