<article>
    <h1>Formulaire de contact</h1>
    <section>
        <h2>Contactez nous</h2>
        <p>Vous pouvez nous contacter pour :</p>
        <ul class="list">
            <li>devenir partenaire de l'événement</li>
            <li>obtenir plus d'informations sur l'événement</li>
            <li>nous informer d'un probleme sur le site web</li>
        </ul>
        <p>N'hésitez pas a nous rejoindre sur <a href="https://www.twitter.com/datlan_eu">Twitter</a> et <a href="https://www.facebook.com/pages/Datlan-2014/532665236755099">Facebook</a></p>
        <form action="" method="post">
            <p><label>Nom :</label><?= $form->getElement('lastname')->render() ?></p>
            <p><label>Prenom :</label><?= $form->getElement('firstname')->render() ?></p>
            <p><label>E-mail :</label><?= $form->getElement('email')->render() ?></p>
            <p><label>Objet :</label><?= $form->getElement('title')->render() ?></p>
            <p><label>Message :</label><?= $form->getElement('body')->render() ?></p>
            <p class="center"><input class="button" type="submit" value="Envoyer le message" /></p>
        </form>
    </section>
</article>
