<article>
    <h1>Datlan, being the best is not enough !</h1>
    <section>
        <h2>La LAN</h2>
        <p>La <b>Datlan</b> est l'événement des joueurs à <b>Nancy</b>. Organisée dans les locaux d'Epitech, la <b>Datlan</b> vous offrira un week-end d'esport fort en émotion. Elle se déroulera en <b>Mars 2014</b>.</p>
        <p>Cette LAN aura pour but de promouvoir l'esport en France mais aussi un projet de 4 étudiants d'Epitech : <b>WrisletCard</b>. Ce projet sera utilisé par tous les joueurs pour payer les consommations.</p>
    </section>
    <section>
        <h2>Les jeux</h2>
        <a href="/leagueoflegend">
        <div class="w50"><div class="game" style="background:url('images/game/lol.jpg')">
            <h3>League of Legends</h3>
            <p>Cliquez pour plus d'informations.                                                  </p>
            <p class="important">24 EQUIPES</p>
        </div></div>
        <a href="/starcraft2">
        <div class="w50"><div class="game" style="background:url('images/game/sc2.jpg')">
            <h3>Starcraft II</h3>
            <p>Cliquez pour plus d'informations.                                                  </p>
            <p class="important">32 JOUEURS</p>
        </div></div>
        </a>
    </section>
    <section>
        <h2>Partenaires</h2>
        <img width="170" src="images/partners/epitech.png" />
    </section>
</article>
