<article>
    <h1>Les informations générales</h1>
    <section>
        <h2>Lieu</h2>
	<p>Epitech Nancy <br />
	80 Rue Saint Georges<br />
	54000 Nancy</p>
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3113.62613634136!2d6.188349200000258!3d48.69260110000174!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4794986b1607f617%3A0xeaf618b4a853f23!2s80+Rue+Saint-Georges%2C+54000+Nancy!5e1!3m2!1sfr!2sfr!4v1390175392440" width="400" height="300" frameborder="0" style="border:0"></iframe>
    </section>
    <section>
        <h2>Dates et horaires</h2>
	<p>Du vendredi 28 mars au dimanche 30 mars 2014</p>
	<p>Ouverture vendredi 28 à 18h</p>
	<p>Fin de la manifestation dimanche 30 à 17h</p>
    </section>
    <section>
        <h2>Divers</h2>
	<p>Les joueurs devront se présenter à l’évènement avec le matériel suivant :</p>
	<ul class=list>
		<li>Votre PC (et la connectique)</li>
		<li>Votre écran (et la connectique)</li>
		<li>Vos périphérique de jeux (clavier, souris, casque, tapis, etc.) <b>Enceintes Interdites</b></li>
		<li>Du liquide pour payer vos repas sur place. Vous pourrez toujours prépayer votre compte en avance par carte bancaire depuis chez vous, et disponible sur place grâce à notre solution de paiement</li>
	</ul>
	<p>Votre ordinateur devrait rempulr les conditions suivantes :</p>
	<ul class=list>
		<li>Votre ordinateur devra être muni d'un logiciel de protection antivirus à jour.</li>
		<li>La dernière version mise à jour sur lequel vous allez jouer en compétition.</li>
		<li>Pour les personnes mineures, une autorisation parentale est indispensable afin de participer à l’évènement. <a href="files/mineurs.pdf">Télécharger l'autorisation parentale.</a></li>
	</ul>
    </section>
    <section>
        <h2>Services</h2>
	<p>Une buvette tenue par nos soins proposera des plats et boissons à moindre coût</p>
	<p>Possibilité de dormir sur place dans les nuits de vendredi à samedi et de samedi à dimanche</p>
	<p>Aucune sortie de matériel entre 00h et 8h du matin</p>
    </section>
    <section>
        <h2>Nota Bene</h2>
	<p>La consommation d'alcool est proscrite dans l'enceinte de l'évènement. Toute personne manifestement saoul pourra être exclue de la manifestation à titre provisoire ou définitif sans pouvoir prétendre à un remboursement total ou partiel.La consommation d'alcool est proscrite dans l'enceinte de l'évènement. Toute personne manifestement saoul pourra être exclue de la manifestation à titre provisoire ou définitif sans pouvoir prétendre à un remboursement total ou partiel.</p>
	<p>Il est également prohibé de fumer dans l'enceinte de l'événement (une zone fumeur sera mise en place).</p>
    </section>
</article>

