<article>
    <h1>League of Legend</h1>
    <section>
         <div class="w50">
            <div class="game" style="background:url('images/game/lol.jpg')"><br /><br /><br /></div>
        </div>
        <div class="w50">
            <table width="100%">
                <tr><td><p>Équipes maximum</p></td><td align="right"><p>24</p></td></tr>
                <tr><td><p>Équipes validées</td><td align="right"><p>0</p></td></tr>
                <tr><td><p>Équipes pré-inscrite</td><td align="right"><p>X</p></td></tr>
            </table>
        </div>
    </section>
</article>