<article>
    <h1>Mentions légales</h1>
    <section>
    	<p><strong>Propriétaire</strong> : Association Dat Events –  80 rue Saint Georges - 54000 Nancy<br />
		<strong>Créateur</strong>  : <a href="http://www.datlan.fr">Dat Events</a><br />
		<strong>Responsable publication</strong> : Grosjean Cyril – c.grosjean {aT} datlan.eu<br />
		Le responsable de la publication est une personne physique.<br />
		<strong>Webmaster</strong> : Grosjean Cyril – c.grosjean {aT} datlan.eu<br />
		<strong>Hébergeur</strong> : OVH SAS – 140 Quai du Sartel 59100 Roubaix - France<br />
    </section>
</article>

