<article>
    <h1>Les partenaires de notre événement</h1>
    <section>
        <h2>Partenaire Principal</h2>
        <div><center></center></div>
    </section>
        <section>
        <h2>Partenaires Silvers</h2>
        <div class="w50"><center></center></div><div class="w50"><center></center></div>
    </section>
        <section>
        <h2>Partenaires technique et logistique</h2>
        <div class="w50"><center><img src="images/partners/epitech.png" /></center></div><div class="w50"><center><img src="images/partner/lana.png" /></center></div>
        <div class="w50"><center><img src="images/partner/mfjv.png" /></center></div><div class="w50"><center></center></div>
    </section>
</article>
