<article>
    <h1>Les partenaires de notre événement</h1>
    <section>
        <h2>Partenaire Principal</h2>
        <div><center></center></div>
    </section>
        <section>
        <h2>Partenaires Silvers</h2>
        <div class="w50"><center></center></div><div class="w50"><center></center></div>
    </section>
        <section>
        <h2>Partenaires technique et logistique</h2>
        <div class="w50"><center><a href="http://www.epitech.eu/"><img style="margin-bottom:20px;" src="images/partners/epitech.png" /></a></center></div><div class="w50"><center><a href="http://www.lana-france.com/"><img src="images/partners/lana.png" style="margin-bottom:20px;" height="73" /></a></center></div>
        <div class="w50"><center><a href="http://www.mastersjeuvideo.org/"><img src="images/partners/mfjv.png" style="margin-bottom:20px;" height="73" /></center></div><div class="w50"><center></center></div>
    </section>
</article>
