<article>
    <h1>Felicitation !</h1>
    <section>
        <?php if ($user == false): ?>
        <h2>Votre compte est deja active ou votre cle n'est plus valide</h2>
        <p>Vous pouvez vous connecter ou nous contacter si vous avez rencontre un probleme.</p>
        <?php else: ?>
        <h2>Votre compte est maintenant active</h2>
        <p>Vous pouvez maintenant vous connecter et vous inscrire au jeux video de votre choix !</p>
        <?php endif; ?>
    </section>
</article>
