<article>
    <h1> Bienvenue sur ton compte </h1>
    <section>
	<h2>Inscription et Paiement</h2>
	<p>Les inscriptions sont ouvertes. Elle vous assurera une place à la première édition de la Datlan.</p>
	<p>Comment s'inscrire ?<br />Il vous suffit de payer votre place grâce au bouton ci-dessous.</p>
	<?php if ($user->getPayment() == 0): ?>
	    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top" class="center">
		<input type="hidden" name="cmd" value="_s-xclick">
		<input type="hidden" name="hosted_button_id" value="B5Y7F4MMH3TKA">
		<input name="custom" type="hidden" value="<?=$user->getId() ?>" />
		<input type="image" src="https://www.paypalobjects.com/fr_FR/FR/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal - la solution de paiement en ligne la plus simple et la plus sécurisée !">
		<img alt="" border="0" src="https://www.paypalobjects.com/fr_FR/i/scr/pixel.gif" width="1" height="1">
	    </form>
	<?php else: ?>
		<h3 class="center">Vous êtes inscrit</h3>
		<p class="center">Nous vous attendons le Vendredi 28 Mars à 18h avec votre PC.</p>	
	<?php endif; ?>
    </section>
    <section>
        <?php if ($user->getStarcraft() == 1): ?>
        <h2>League of legends : non inscrit</h2>
        <?php elseif($team != false): ?>
        <h2>League of legends : <?php echo ($user->getPayment() == 1) ? "inscrit" : "pré-inscrit"; ?> <a href="?id=<?= $user->getTeam(); ?>">(Se désinscrire du tournoi)</a></h2>
	<?php
	$payment = 0;
	foreach ($usersTeam as $userTeam) {
		if ($userTeam->getPayment() != 0)
			$payment++;
	}
	?>
        <h3>Team : <?php echo $team->getName() ?> (<?php echo $team->getTag() ?>) - <?php echo $payment; ?> / 5</h3>
        <ul class="list">
        <?php foreach($usersTeam as $userTeam): ?>
        <li><span class="<?php echo ($userTeam->getPayment() == 1) ? "green" : "red"; ?>"><?= htmlentities($userTeam->getFirstname()) . ' "' . htmlentities($userTeam->getUsername()) . '" ' . htmlentities($userTeam->getLastname()) ?></span></li>
        <?php endforeach; ?>
        </ul>
        <?php else: ?>
        <h2>League of legends : non inscrit</h2>
        <div class="w50">
            <h3>Créer une team</h3>
            <?php if ($createForm->hasError()): ?>
            <div class="error">
            <ul class="list">
            <?php foreach ($createForm->getErrors() as $error): ?>
                <li><?php echo $error; ?></li>
            <?php endforeach; ?>
            </ul>
            </div>
            <?php endif; ?>
            <form action="" method="post">
            <p class="small"><label>Nom </label><?=$createForm->getElement('name')->render(); ?></p>
            <p class="small"><label>Tag </label><?=$createForm->getElement('tag')->render(); ?></p>
            <p class="small"><label>Mot de passe </label><?=$createForm->getElement('password')->render(); ?></p>
            <p class="small"><label>Confirmation </label><?=$createForm->getElement('password2')->render(); ?></p>
            <p class="center"><input class="button" type="submit" name="submit-create" value="Creer" /></p>
            </form>
        </div>
        <div class="w50">
            <h3>Entrer dans une team</h3>
            <?php if ($joinForm->hasError()): ?>
            <div class="error">
            <ul class="list">
            <?php foreach ($joinForm->getErrors() as $error): ?>
                <li><?php echo $error; ?></li>
            <?php endforeach; ?>
            </ul>
            </div>
            <?php endif; ?>
            <form action="" method="post">
            <p class="small"><label>Tag </label><?=$joinForm->getElement('tag')->render(); ?></p>
            <p class="small"><label>Mot de passe </label><?=$joinForm->getElement('password')->render(); ?></p>
            <p class="center"><input class="button" type="submit" name="submit-join" value="Rejoindre" /></p>
            </form>
        </div>
        <?php endif; ?>
        <div style="clear: both;"></div>
    </section>
    <section>
        <?php if ($team != false): ?>
        <h2>Starcraft II : non inscrit</h2>
        <?php elseif ($user->getStarcraft() == 1): ?>
        <h2>Starcraft II : <?php echo ($user->getPayment() == 1) ? "inscrit" : "pré-inscrit"; ?> <a href="?starcraft=n">(Se désinscrire du tournoi)</a></h2>
        <?php else: ?>
        <h2>Starcraft II : non inscrit</h2>
        <p><a href="?starcraft=y">S'inscrire</a></p>
        <?php endif; ?>
    </section>
</article>
