<article>
    <h1> Bienvenue sur ton compte </h1>
    <section>
	<p>Vous pouvez vous pré-inscrire dans l'un des tournois dès maintenant, cela vous permettra d'avoir la possibilité d'être au courant lors de la phase de paiements par mail.</p>
	<p>La phase d'inscription (et donc de paiement) sera ouverte d'ici peu.</p>
    </section>
    <section>
        <?php if ($user->getStarcraft() == 1): ?>
        <h2>League of legends : non inscrit</h2>
        <?php elseif($team != false): ?>
        <h2>League of legends : pré-inscrit <a href="?id=<?= $user->getTeam(); ?>">(Se desinscrire)</a></h2>
        <h3>Team : <?php echo $team->getName() ?> (<?php echo $team->getTag() ?>)</h3>
        <ul class="list">
        <?php foreach($usersTeam as $userTeam): ?>
        <li><?= htmlentities($userTeam->getFirstname()) . ' "' . htmlentities($userTeam->getUsername()) . '" ' . htmlentities($userTeam->getLastname()) ?></li>
        <?php endforeach; ?>
        </ul>
        <?php else: ?>
        <h2>League of legends : non inscrit</h2>
        <div class="w50">
            <h3>Créer une team</h3>
            <?php if ($createForm->hasError()): ?>
            <div class="error">
            <ul class="list">
            <?php foreach ($createForm->getErrors() as $error): ?>
                <li><?php echo $error; ?></li>
            <?php endforeach; ?>
            </ul>
            </div>
            <?php endif; ?>
            <form action="" method="post">
            <p class="small"><label>Nom </label><?=$createForm->getElement('name')->render(); ?></p>
            <p class="small"><label>Tag </label><?=$createForm->getElement('tag')->render(); ?></p>
            <p class="small"><label>Mot de passe </label><?=$createForm->getElement('password')->render(); ?></p>
            <p class="small"><label>Confirmation </label><?=$createForm->getElement('password2')->render(); ?></p>
            <p class="center"><input class="button" type="submit" name="submit-create" value="Creer" /></p>
            </form>
        </div>
        <div class="w50">
            <h3>Entrer dans une team</h3>
            <?php if ($joinForm->hasError()): ?>
            <div class="error">
            <ul class="list">
            <?php foreach ($joinForm->getErrors() as $error): ?>
                <li><?php echo $error; ?></li>
            <?php endforeach; ?>
            </ul>
            </div>
            <?php endif; ?>
            <form action="" method="post">
            <p class="small"><label>Tag </label><?=$joinForm->getElement('tag')->render(); ?></p>
            <p class="small"><label>Mot de passe </label><?=$joinForm->getElement('password')->render(); ?></p>
            <p class="center"><input class="button" type="submit" name="submit-join" value="Rejoindre" /></p>
            </form>
        </div>
        <?php endif; ?>
        <div style="clear: both;"></div>
        <?php if ($team != false): ?>
        <h2>Starcraft II : non inscrit</h2>
        <?php elseif ($user->getStarcraft() == 1): ?>
        <h2>Starcraft II : pré-inscrit <a href="?starcraft=n">(Se desinscrire)</a></h2>
        <?php else: ?>
        <h2>Starcraft II : non inscrit</h2>
        <p><a href="?starcraft=y">S'inscrire</a></p>
        <?php endif; ?>
    </section>
</article>
