<!DOCTYPE html>
<html lang="fr">
<head>
    <title>Datlan, being the best is not enough</title>
    <meta charset="utf-8" />

    <link rel="stylesheet" media="all" href="http://fonts.googleapis.com/css?family=PT+Sans+Narrow">
    <link rel="stylesheet" href="css/screen.css" />

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="js/jquery.vegas.min.js"></script>
    <script src="js/main.js"></script>
</head>
<body>
    <header id="header">
        <div class="container">
            <h1><img height="60" src="/images/logo.png" title="Datlan" alt="Datlan" /></h1>
            <nav id="nav">
                <ul>
                    <li><a href="/">Accueil</a></li>
                    <li><a href="/stands">Infos</a></li>
                    <li><a href="/contact">Contact</a></li>
                    <?php if ($auth->hasIdentity()): ?>
                    <li><a href="/account">Mon compte</a></li>
                    <li><a href="/logout">Se deconnecter</a></li>
                    <?php else: ?>
                    <li><a href="/register">S'inscrire</a></li>
                    <li><a href="/login">Se connecter</a></li>
                    <?php endif; ?>
                </ul>
            </nav>
        </div>
    </header>
    <div class="container">
        <?= $content ?>
    </div>
    <footer id="footer">
        <div class="container">
            &copy; Copyright Datlan 2014
        </div>
    </footer>
</body>
</html>
