<!DOCTYPE html>
<html lang="fr">
<head>
    <title>Datlan, being the best is not enough</title>
    <meta charset="utf-8" />

    <link rel="stylesheet" media="all" href="http://fonts.googleapis.com/css?family=PT+Sans+Narrow">
    <link rel="stylesheet" href="css/screen.css" />

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="js/jquery.vegas.min.js"></script>
    <script src="js/main.js"></script>
</head>
<body>
    <header id="header">
        <div class="container">
            <h1>Datlan</h1>
            <nav id="nav">
                <ul>
                    <li><a href="">Accueil</a></li>
                    <li><a href="">Les stands</a></li>
                    <li><a href="">Contacts</a></li>
                    <li><a href="">Mon compte</a></li>
                </ul>
            </nav>
        </div>
    </header>
    <div class="container">
        <?= $content ?>
    </div>
    <footer id="footer">
        &copy; Copyright Datlan 2014
    </footer>
</body>
</html>
