<!DOCTYPE html>
<html lang="fr">
<head>
    <title>Datlan, being the best is not enough</title>
    <meta charset="utf-8" />

    <link rel="stylesheet" media="all" href="http://fonts.googleapis.com/css?family=PT+Sans+Narrow">
    <link rel="stylesheet" href="css/screen.css" />

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script src="js/jquery.vegas.min.js"></script>
    <script src="js/main.js"></script>
</head>
<body>
    <header id="header">
        <div class="container">
            <h1><a href="/"><img height="60" src="/images/logo.png" title="Datlan" alt="Datlan" /></a></h1>
            <nav id="nav">
                <ul>
                    <li><a href="/news">News</a></li>
                    <li><a href="/infos">Infos</a></li>
                    <li><a href="http://forum.datlan.eu">Forum</a></li>
<!--                <li><a href="/stands">Stands</a></li> 
                    <li><a href="/partners">Partenaires</a></li> -->
                    <li><a href="/contact">Contact</a></li>
                    <?php if ($auth->hasIdentity()): ?>
                    <li><a href="/account">Mon compte</a></li>
                    <li><a href="/logout">Se déconnecter</a></li>
                    <?php else: ?>
                    <li><a href="/register">S'inscrire</a></li>
                    <li><a href="/login">Se connecter</a></li>
                    <?php endif; ?>
                </ul>
                <a class="social" href="https://www.twitter.com/datlan_eu"><img src="images/social/twitter.png" /></a>
                <a class="social"href="https://www.facebook.com/pages/Datlan-2014/532665236755099"><img src="images/social/facebook.png" /></a>
            </nav>
        </div>
    </header>
    <div class="container">
        <?= $content ?>
    </div>
    <footer id="footer">
        <div class="container">
            &copy; Copyright Datlan 2014 - <a href="/confidentiality">Confidentialité</a>
        </div>
    </footer>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47319803-1', 'datlan.eu');
  ga('send', 'pageview');

</script>
</body>
</html>
