<article>
    <h1>League of Legend</h1>
    <section>
         <div class="w50">
            <div class="game" style="background:url('images/game/lol.jpg')"><br /><br /><br /><br /><br /><br /><br /></div>
        </div>
        <div class="w50">
            <p>
            <table width="100%">
                <tr><td>Équipes maximum</b></td><td align="right">24</td></tr>
                <tr><td><b>Équipes validées</b></td><td align="right">0</td></tr>
                <tr><td>Équipes pré-inscrite</td><td align="right"><?php echo $registeredTeams ?></td></tr>
                <tr></tr>
                <tr><td><b>Reglement du tournoi : </b></td><td align="right"><a href="files/leagueoflegend/reglement.pdf">Lien</a></td></tr>
                <tr><td><b>Planning du tournoi : </b></td><td align="right"><a href="files/leagueoflegend/planning.pdf">Lien</a></td></tr>
            </table>
            </p>
        </div>
    </section>
    <?php if ($validedTeams > 0): ?>
    <section>
        <h2>Equipes validées :</h2>
        <div></div>
    </section>
    <?php endif; ?>
    <?php if ($registeredTeams > 0): ?>
    <section>
        <h2>Equipes pré-inscrites :</h2>
        <div>
        </div>
    </section>
    <?php endif; ?>
</article>