<article>
    <h1>League of Legend</h1>
    <section>
         <div class="w50">
            <div class="game" style="background:url('images/game/lol.jpg')"><br /><br /><br /><br /><br /><br /></div>
        </div>
        <div class="w50">
            <table width="100%">
                <tr><td><h3>Équipes maximum</h3></td><td align="right"><h3>24</h3></td></tr>
                <tr><td><h3>Équipes validées</h3></td><td align="right"><h3>0</h3></td></tr>
                <tr><td><h3>Équipes pré-inscrite</h3></td><td align="right"><h3>X</h3></td></tr>
            </table>
        </div>
    </section>
</article>