<article>
    <h1>Starcraft 2 : Heart of the Swarm   </h1>
    <section>
         <div class="w50">
            <div class="game" style="background:url('images/game/sc2.jpg')"><br /><br /><br /><br /><br /><br /><br /></div>
        </div>
        <div class="w50">
        <p>
            <table width="100%">
                <tr><td>Joueurs maximum</td><td align="right">24</td></tr>
                <tr><td><b>Joueurs validés</b></td><td align="right"><?php echo $validedPlayers ?></td></tr>
                <tr><td>Joueurs pré-inscrit</td><td align="right"><?php echo $registeredPlayers ?></td></tr>
                <tr></tr>
                <tr><td><b>Reglement du tournoi</b></td><td align="right"><a href="files/starcraft2/reglement.pdf">Lien</a></td></tr>
                <tr><td><b>Planning du tournoi</b></td><td align="right"><a href="files/starcraft2/planning.pdf">Lien</a></td></tr>
            </table>
        </p>
        </div>
    </section>
    <?php if ($validedPlayers > 0): ?>
    <section>
        <h2>Joueurs validés :</h2>
        <div></div>
    </section>
    <?php endif; ?>
    <?php if ($registeredPlayers > 0): ?>
    <section>
        <h2>Joueurs pré-inscrits :</h2>
        <p>
            <table width="100%">
            <?php foreach($registeredPlayersList as $value) { ?>
                <tr><td width="5%"></td><td><?php echo $value->getUsername() ?></td></tr>
           <?php } ?>
            </table>
        </p>
    </section>
    <?php endif; ?>
</article>
