<article>
    <h1>Starcraft 2 : Heart of the Swarm   </h1>
    <section>
         <div class="w50">
            <div class="game" style="background:url('images/game/lol.jpg')"><br /><br /><br /><br /><br /><br /><br /><br /></div>
        </div>
        <div class="w50">
            <table width="100%">
                <tr><td>Joueurs maximum</td><td align="right">24</td></tr>
                <tr><td>Joueurs validées</td><td align="right">0</td></tr>
                <tr><td>Joueurs pré-inscrite</td><td align="right"><?php echo $registeredPlayers ?></td></tr>
            </table>
        </div>
    </section>
</article>
