<article>
    <h1>Starcraft 2 : Heart of the Swarm   </h1>
    <section>
         <div class="w50">
            <div class="game" style="background:url('images/game/sc2.jpg')"><br /><br /><br /><br /><br /><br /><br /><br /></div>
        </div>
        <div class="w50">
            <table width="100%">
                <tr><td>Joueurs maximum</td><td align="right">24</td></tr>
                <tr><td>Joueurs validés</td><td align="right">0</td></tr>
                <tr><td>Joueurs pré-inscrit</td><td align="right"><?php echo $registeredPlayers ?></td></tr>
            </table>
            <br />
            <p><b>Reglement du tournoi : </b> <a href="files/starcarft2/reglement.pdf">Lien</a></p>
            <p><b>Planning du tournoi : </b> <a href="files/starcraft2/planning.pdf">Lien</a></p>
        </div>
    </section>
</article>
