<article>
    <h1>Actualité Datlan !</h1>
    <?php if (count($news) > 0): ?>
        <?php foreach($news as $new): ?>
        <section>
        <h2 style='float:left'><?php echo $new->getTitle(); ?></h2>
        <div style='float:right;margin-top:25px'><?php echo 'Le '.$new->getDate().' par '.$new->getBy(); ?></div>
        <div style='clear:both;text-align:justify'><?php echo $new->getContent(); ?></div>
        </section>
        <?php endforeach; ?>
    <?php else: ?>
        <section>
        <h2>Aucune news</h2>
        </section>
    <?php endif; ?>
</article>
